name: hawk-sensor-health 
version: v1alpha
type: lens
tags:
  - Tier.Gold
  - Domain.Water Management
  - dataos:resource:lens
description: Lens model providing structured access to Hawk sensor telemetry, including sensor readings, GPS data, irrigation events, weather forecasts, and device health metrics for analytics and monitoring.
# workspace: arable
lens:
  compute: arable-compute
  # secrets:
  #   - name: 
  #     allKeys: true
  source:
    type: minerva
    name: arablecluster
    catalog: lakehouse
  repo:  
    url: https://bitbucket.org/tmdc/arable
    lensBaseDir: arable/poc/sensor-health-semantic-model/hawk-sensor-health/model
    syncFlags:
      - --ref=main
  api:   # optional
    replicas: 1 # optional
    logLevel: info  # optional
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  worker: # optional
    replicas: 1 # optional
    logLevel: info  # optional
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:   
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  router: # optional
    logLevel: info  # optional
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
